<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Site Supervisor  Sample Organization</name>
   <tag></tag>
   <elementGuidId>f0c22fce-fdc8-41ae-9cbd-fc0a9628719b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//li[@id=''])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>98a0fa0e-3527-4bf4-b556-390197efefd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>75ff2ea3-faf4-4a52-aef0-ef66700d9d98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-ripple p-element p-autocomplete-item ng-tns-c329-48 ng-star-inserted</value>
      <webElementGuid>5a1be089-a5b3-4a43-80a4-f152272de7fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>85fee2fe-8eab-48ef-8bea-5987037b310a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Site Supervisor | Sample Organization </value>
      <webElementGuid>8b45b458-aaea-4705-92b1-53111b2e17e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_27_list&quot;)/li[@class=&quot;p-ripple p-element p-autocomplete-item ng-tns-c329-48 ng-star-inserted&quot;]</value>
      <webElementGuid>fb4f3fbd-c358-40e6-aec7-7d663e146fc3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//li[@id=''])[4]</value>
      <webElementGuid>c2e3bd4b-5bd8-4566-8941-fbf25dab6fd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='pr_id_27_list']/li[4]</value>
      <webElementGuid>a7e36ea7-9bb8-4daf-b03b-4292d8ae5e99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/ul/li[4]</value>
      <webElementGuid>04895646-32f6-456e-a6b4-ec3a6e8cbbf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Site Supervisor | Sample Organization ' or . = 'Site Supervisor | Sample Organization ')]</value>
      <webElementGuid>d1af60da-4248-4b7d-8932-2f99a02f5e66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
