<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>adminemail</name>
   <tag></tag>
   <elementGuidId>8ad2e204-821b-425c-aa88-0ab5bfd58650</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html[1]/body[1]/qm-root[1]/qmt-layout[1]/qmt-navigation[1]/mat-sidenav-container[1]/mat-sidenav-content[1]/div[1]/div[1]/qmt-company-form[1]/form[1]/div[1]/div[1]/qmt-new-input[7]/div[1]/input[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/qm-root[1]/qmt-layout[1]/qmt-navigation[1]/mat-sidenav-container[1]/mat-sidenav-content[1]/div[1]/div[1]/qmt-company-form[1]/form[1]/div[1]/div[1]/qmt-new-input[7]/div[1]/input[1]</value>
      <webElementGuid>9093759c-3cb5-4e0a-b388-a369c7409790</webElementGuid>
   </webElementProperties>
</WebElementEntity>
