<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>adminfirstname</name>
   <tag></tag>
   <elementGuidId>aa4d5415-cf1b-44d4-8129-1bb3754a1310</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html[1]/body[1]/qm-root[1]/qmt-layout[1]/qmt-navigation[1]/mat-sidenav-container[1]/mat-sidenav-content[1]/div[1]/div[1]/qmt-company-form[1]/form[1]/div[1]/div[1]/qmt-new-input[5]/div[1]/input[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/qm-root[1]/qmt-layout[1]/qmt-navigation[1]/mat-sidenav-container[1]/mat-sidenav-content[1]/div[1]/div[1]/qmt-company-form[1]/form[1]/div[1]/div[1]/qmt-new-input[5]/div[1]/input[1]</value>
      <webElementGuid>66ad0784-3fb4-45b5-86bf-347f6630771e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
