<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_person User Management</name>
   <tag></tag>
   <elementGuidId>1a0300c2-5238-4eab-860c-721da8cbfc4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.anml-data.ng-tns-c177-14.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f9ae717a-31c5-4231-aa76-a19ee7887708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>anml-data ng-tns-c177-14 ng-star-inserted</value>
      <webElementGuid>d5e8f771-f452-4ea1-af15-2ade6bcac62a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>b0a26259-a193-4ffd-b3c3-e0387649b36e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>64b71447-1f69-44c6-b521-da93b8bb35d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> person User Management</value>
      <webElementGuid>0e14dc0f-5691-4d63-b275-c0f8ad37d5f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography mat-app-background&quot;]/qm-root[1]/qmt-layout[@class=&quot;ng-star-inserted&quot;]/qmt-navigation[1]/mat-sidenav-container[@class=&quot;mat-drawer-container mat-sidenav-container sidenav-container&quot;]/mat-sidenav[@class=&quot;mat-drawer mat-sidenav sidenav relative ng-tns-c183-1 ng-trigger ng-trigger-transform mat-drawer-side mat-drawer-opened mat-sidenav-fixed ng-star-inserted&quot;]/div[@class=&quot;mat-drawer-inner-container ng-tns-c183-1&quot;]/ng-material-multilevel-menu[@class=&quot;ng-tns-c183-1&quot;]/div[@class=&quot;amml-container my-custom-class normal-case ng-star-inserted&quot;]/mat-list[@class=&quot;mat-list mat-list-base&quot;]/ng-list-item[@class=&quot;ng-tns-c177-14 ng-star-inserted&quot;]/div[@class=&quot;amml-menu-container ng-tns-c177-14&quot;]/mat-list-item[@class=&quot;mat-list-item mat-focus-indicator mat-ripple ng-tns-c177-14 amml-item selected-amml-item level-1-submenulevel-0 ng-star-inserted&quot;]/span[@class=&quot;mat-list-item-content&quot;]/a[@class=&quot;anml-link ng-tns-c177-14 ng-star-inserted&quot;]/div[@class=&quot;anml-data ng-tns-c177-14 ng-star-inserted&quot;]</value>
      <webElementGuid>10f59014-1dd7-4194-9014-7586ae3dfc07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div</value>
      <webElementGuid>4a48fd73-2a34-4315-bfcc-2916a58dae4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' person User Management' or . = ' person User Management')]</value>
      <webElementGuid>3bd33c51-8e35-46d7-bbc7-f300258c9df1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
