<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputmat-checkbox-34-input</name>
   <tag></tag>
   <elementGuidId>392d066f-0a1e-4bd7-9ebd-1834c2bdca79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-checkbox-34-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mat-checkbox-34-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9697130d-34e2-4041-9338-f8d062f3be35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>ef237045-5506-4ba4-b5c6-41f1ea0c52b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-checkbox-input cdk-visually-hidden</value>
      <webElementGuid>614edaa2-a675-40d3-87e2-c0f5fd8c1ae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-checkbox-34-input</value>
      <webElementGuid>0b98734c-8ac7-4048-858e-6933de6a5372</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4530e49e-25f1-4422-adcc-cd37731ddd9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>39bf821c-67ea-4cc2-9f5b-7206c589d15e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-checkbox-34-input&quot;)</value>
      <webElementGuid>afc26dc8-7818-4d23-9d53-9b343fc42270</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mat-checkbox-34-input']</value>
      <webElementGuid>b22b2b92-52a7-4002-adac-7291bbd68c78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-checkbox[@id='mat-checkbox-34']/label/span/input</value>
      <webElementGuid>c35dcf0f-06b8-401b-9a5f-34cb615a8d03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/mat-checkbox/label/span/input</value>
      <webElementGuid>1bccb903-c7f2-4c39-a237-9c6083b654c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'mat-checkbox-34-input']</value>
      <webElementGuid>0f289f20-d3c6-401b-9cf3-6cbd2c59fdee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
