<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputmat-checkbox-14-input</name>
   <tag></tag>
   <elementGuidId>9cbc9fe8-b6b1-44ba-98bf-101096609bc9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-checkbox-14-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mat-checkbox-14-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>755245cd-bfb7-41e1-9f59-35ea45db7f82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>9ac40328-7eb3-4127-8ae3-b9fe6856375b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-checkbox-input cdk-visually-hidden</value>
      <webElementGuid>8a15930b-869f-4e7d-8a43-711f4e0b1358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-checkbox-14-input</value>
      <webElementGuid>b212f7c6-af4d-4c47-af50-61366e6553c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>657347e4-5a15-4031-b164-75a359a6d927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e043badb-3fc8-4a2c-989a-a65b49a27223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-checkbox-14-input&quot;)</value>
      <webElementGuid>725389db-8c4c-472c-b993-ed2280007467</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mat-checkbox-14-input']</value>
      <webElementGuid>1f216c19-7c8c-4d25-944e-ea413b667b6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-checkbox[@id='mat-checkbox-14']/label/span/input</value>
      <webElementGuid>9da65147-9352-4122-9592-dbd5002286ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/mat-checkbox/label/span/input</value>
      <webElementGuid>c91989d0-c7c0-4133-8f3e-9e61784992d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'mat-checkbox-14-input']</value>
      <webElementGuid>64a8716e-b607-4fd5-b437-76a632eb8083</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
