<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonrow-delete</name>
   <tag></tag>
   <elementGuidId>5701586d-fcba-4bcc-8e4b-cea3f190479f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#row-delete</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='row-delete']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c2e61442-1c71-4872-9091-e41a99649090</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>row-delete</value>
      <webElementGuid>fb995e23-a7db-4907-b862-b165f67ecd03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-focus-indicator flex justify-center w-[30px] h-[30px] items-center !text-red-500 mat-icon-button mat-button-base ng-star-inserted cdk-focused cdk-mouse-focused</value>
      <webElementGuid>c863015e-2be1-4f83-b4f8-aa658eeb4eb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_42-table&quot;)/tbody[@class=&quot;p-element p-datatable-tbody&quot;]/tr[@class=&quot;ng-star-inserted&quot;]/td[@class=&quot;!border-b-gray-A1 !flex-1 !p-4 text-gray-A3 truncate ng-star-inserted&quot;]/div[1]/div[@class=&quot;flex justify-start items-center h-full w-full gap-2 ng-star-inserted&quot;]/button[@id=&quot;row-delete&quot;]</value>
      <webElementGuid>5a7ab92a-73b1-4bb8-adad-f93d3d6091a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='row-delete']</value>
      <webElementGuid>d68f5ea1-d86e-4ec5-98a8-48ec64cd3427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='pr_id_42-table']/tbody/tr/td[7]/div/div/button</value>
      <webElementGuid>a4c734c9-a576-490d-ac26-4d0d89afce8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/div/div/button</value>
      <webElementGuid>e45403e0-9733-46f5-9c48-d8bd06caa1f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'row-delete']</value>
      <webElementGuid>393c224b-7bb7-4937-8a24-4b876fcadfd9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
