<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>click_on_profile</name>
   <tag></tag>
   <elementGuidId>924fc9a9-f4e1-4e50-8826-081a76b9c638</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>_ngcontent-iim-c142</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>_ngcontent-iim-c142</value>
      <webElementGuid>9288cace-2e6b-49d5-ab0e-99a9202b9449</webElementGuid>
   </webElementProperties>
</WebElementEntity>
