<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputModel</name>
   <tag></tag>
   <elementGuidId>2bd34538-2efc-4fdd-8ca5-0d58dbce870f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Model</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Model']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8d9da895-c726-492d-91dc-9c5128b4e9c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-element !w-full p-inputtext-sm ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>f47039ec-e6eb-4b48-9350-102d7ed1e840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Model</value>
      <webElementGuid>183b08cb-1a66-4282-8ddb-55de5defee2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6a52fcee-eec5-4fd9-a9ea-45675589ff8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Add text here</value>
      <webElementGuid>be384055-369a-43ff-845c-a54f04fa5cd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-form</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>454268b3-bbd6-47fd-a7b2-985607ee62a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>undefined</value>
      <webElementGuid>fd8edb42-5d73-45d9-9103-9b15a74e86fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>undefined</value>
      <webElementGuid>cbb222c9-4845-4782-8433-cd9eb4606da8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Model&quot;)</value>
      <webElementGuid>40d9946b-6e01-4581-b76b-081b1e605d0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Model']</value>
      <webElementGuid>8eb60f3b-30e0-4899-87e9-fcaa11497df6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//qmt-new-input[4]/div/input</value>
      <webElementGuid>2aad9a5c-d771-4ba4-954e-ca3a448e5f8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Model' and @type = 'text' and @placeholder = 'Add text here']</value>
      <webElementGuid>2ce43f0d-493b-4bd6-95a9-084160fba945</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
