<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Company Users</name>
   <tag></tag>
   <elementGuidId>0b7d0357-2afd-4eea-bf61-3ce7aeb542f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html[1]/body[1]/qm-root[1]/qmt-layout[1]/qmt-navigation[1]/mat-sidenav-container[1]/mat-sidenav[1]/div[1]/ng-material-multilevel-menu[1]/div[1]/mat-list[1]/ng-list-item[2]/div[1]/div[1]/ng-list-item[2]/div[1]/mat-list-item[1]/span[1]/a[1]/div[1]/span[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html[1]/body[1]/qm-root[1]/qmt-layout[1]/qmt-navigation[1]/mat-sidenav-container[1]/mat-sidenav[1]/div[1]/ng-material-multilevel-menu[1]/div[1]/mat-list[1]/ng-list-item[2]/div[1]/div[1]/ng-list-item[2]/div[1]/mat-list-item[1]/span[1]/a[1]/div[1]/span[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.label.ng-tns-c125-29</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c2cf88ee-09d6-4c27-a5ff-92c491ca8cb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>label ng-tns-c125-29</value>
      <webElementGuid>7ffa40b9-10b6-4e95-81f1-467f3049dffd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Company Users</value>
      <webElementGuid>2a6a2859-7236-425e-a50c-3f08ea8e9e25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/qm-root[1]/qmt-layout[1]/qmt-navigation[1]/mat-sidenav-container[1]/mat-sidenav[1]/div[1]/ng-material-multilevel-menu[1]/div[1]/mat-list[1]/ng-list-item[2]/div[1]/div[1]/ng-list-item[2]/div[1]/mat-list-item[1]/span[1]/a[1]/div[1]/span[1]</value>
      <webElementGuid>23f209c5-c697-4c47-ab09-3944b0369e25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Company User</value>
      <webElementGuid>897e5db1-35c2-43bd-9bdf-1669211e9519</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ng-list-item[2]/div/mat-list-item/span/a/div/span</value>
      <webElementGuid>44b36720-cc16-4ebf-882a-2d60b09d4a17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Company Users' or . = 'Company Users')]</value>
      <webElementGuid>210d2ecc-8a89-48e0-920b-44e52dd0da55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
