<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputEmployee Type Name</name>
   <tag></tag>
   <elementGuidId>651949ef-2f22-497a-a83c-9d56998b64f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Employee Type Name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e96fa479-16f1-4d91-9812-0a40ea17ecc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-element !w-full p-inputtext-sm ng-untouched ng-pristine</value>
      <webElementGuid>7319ce87-819b-4aad-aac9-87e8f9af3057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Employee Type Name</value>
      <webElementGuid>edeb77d5-4df7-4e64-98ca-cb4624521805</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c17b4469-446f-4599-9d0f-3c3ac5a4726a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>undefined</value>
      <webElementGuid>544d01c0-257c-40a3-8689-d3c8e92d6723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>undefined</value>
      <webElementGuid>0ea06af6-fbc4-4176-ac46-ad5fa609efab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Employee Type Name&quot;)</value>
      <webElementGuid>9a6d13c3-7c7d-4fd9-8cd0-5d991b328d73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Employee Type Name']</value>
      <webElementGuid>96f6420d-89be-4cfa-94ea-ceb2bebfc43d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-0']/qmt-employee-type-modal/mat-dialog-content/form/div[2]/qmt-new-input/div/input</value>
      <webElementGuid>8b704c6d-e3b6-47e2-9524-3074b8a5a142</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/qmt-new-input/div/input</value>
      <webElementGuid>8b3b6bd5-92cf-423c-ad74-ad57bc500dcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Employee Type Name' and @type = 'text']</value>
      <webElementGuid>ed24823e-1f1e-41c9-bfc7-fabb68a792ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
