<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Close</name>
   <tag></tag>
   <elementGuidId>530245d0-5273-4bfb-90f9-e136665e38e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dialog-close</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='dialog-close']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e985cf52-3e1b-4df3-bf76-a4640b88f6c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dialog-close</value>
      <webElementGuid>ccf4306b-c978-4b3d-8afb-573d759ad126</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>warn</value>
      <webElementGuid>ffe4c494-c0ed-4d72-8697-47bae389d08a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-focus-indicator mat-stroked-button mat-button-base mat-warn cdk-focused cdk-mouse-focused</value>
      <webElementGuid>e34c1910-e3ce-46eb-95e1-ba449fb76923</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-color</name>
      <type>Main</type>
      <value>warn</value>
      <webElementGuid>9986dc4d-7643-4299-985a-9afe94d06630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6eee444b-60c6-4c17-934c-36b61a489317</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>ea36cdee-b843-4373-b4dc-790bc682e609</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dialog-close&quot;)</value>
      <webElementGuid>de446ce6-3f4b-4ec5-a40f-06e5d70aad99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='dialog-close']</value>
      <webElementGuid>beb914e2-ff03-498e-8d09-7eaa90bda43e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-1']/qmt-job-title-modal/mat-dialog-content/form/mat-dialog-actions/div/button</value>
      <webElementGuid>95cfe722-6bbb-4643-9a3e-f5c2b8b801e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-dialog-actions/div/button</value>
      <webElementGuid>2b8a97e1-d0f0-4333-8bea-346c112c5e40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'dialog-close' and @type = 'button' and (text() = 'Close' or . = 'Close')]</value>
      <webElementGuid>b7fa9adb-5dcd-473c-9f4e-d8887850de85</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
