<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Role</name>
   <tag></tag>
   <elementGuidId>e950c0e5-e197-4efd-b8ca-19c8af90e0d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.p-element.p-ripple.p-autocomplete-dropdown.ng-tns-c329-60.p-button.p-component.p-button-icon-only.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[11]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'Role']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4680591c-4b10-49b9-9134-2bfdb08cece2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>76c0522c-2f49-4aad-93c8-63b190614ea3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-element p-ripple p-autocomplete-dropdown ng-tns-c329-60 p-button p-component p-button-icon-only ng-star-inserted</value>
      <webElementGuid>58b819e8-0a11-4127-a059-ccc47f4bcd92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-icon</name>
      <type>Main</type>
      <value>pi pi-chevron-down</value>
      <webElementGuid>c75e68e7-2756-4723-9803-61af9ea19e32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> </value>
      <webElementGuid>6ae1a59d-6f6a-44dd-8b04-8723c55eeb53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Role&quot;)/span[@class=&quot;ng-tns-c329-60 p-autocomplete p-component p-autocomplete-dd&quot;]/button[@class=&quot;p-element p-ripple p-autocomplete-dropdown ng-tns-c329-60 p-button p-component p-button-icon-only ng-star-inserted&quot;]</value>
      <webElementGuid>180fc4e0-50dc-4813-bafd-3d53cbf97adc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Role</value>
      <webElementGuid>f712ff6c-a257-4145-b148-2fc0b7aa08b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[11]</value>
      <webElementGuid>0fd8eece-3f1f-4acf-a1ba-837e16480d39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p-autocomplete[@id='Role']/span/button</value>
      <webElementGuid>7c4bea07-2e4a-43ed-9ff9-9b02c18773a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/qmt-new-autocomplete/div/p-autocomplete/span/button</value>
      <webElementGuid>37859a7b-28b1-430e-bb15-f178f4344bb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = ' ' or . = ' ')]</value>
      <webElementGuid>5143493c-01d1-4882-9d7f-26c57879d955</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
