<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_mat-checkbox-inner-container</name>
   <tag></tag>
   <elementGuidId>6aaa618a-d777-4d72-b56e-258a0cf1517e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-checkbox[@id='mat-checkbox-2']/label/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html[1]/body[1]/qm-root[1]/qmt-layout[1]/qmt-navigation[1]/mat-sidenav-container[1]/mat-sidenav-content[1]/div[1]/div[1]/qmt-union-code-form[1]/form[1]/div[1]/div[2]/div[7]/div[1]/div[1]/mat-checkbox[1]/label[1]/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.mat-checkbox-inner-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d495e2e0-a929-4ddf-95fe-2dcd64f992ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-checkbox-inner-container</value>
      <webElementGuid>56cb186c-57b9-480e-8385-db0b010fbc3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/qm-root[1]/qmt-layout[1]/qmt-navigation[1]/mat-sidenav-container[1]/mat-sidenav-content[1]/div[1]/div[1]/qmt-union-code-form[1]/form[1]/div[1]/div[2]/div[7]/div[1]/div[1]/mat-checkbox[1]/label[1]/span[2]</value>
      <webElementGuid>d27ecdf2-10fa-4c17-b13a-7dcc0ae60d7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-checkbox[@id='mat-checkbox-2']/label/span</value>
      <webElementGuid>c15d377e-2a9f-40c8-9eef-dae9ffb36d45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span</value>
      <webElementGuid>d3320fb5-0779-41d8-a3e6-841b5126f57b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
