<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Testing Status</name>
   <tag></tag>
   <elementGuidId>25a4e3d8-1891-4a51-8022-54ba350b86f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.p-ripple.p-element.p-autocomplete-item.ng-tns-c329-52.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>457a77b4-cfd5-4270-8328-6d39ef5b34b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>e94d226a-fcb0-424d-bd08-53997d642af0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-ripple p-element p-autocomplete-item ng-tns-c329-52 ng-star-inserted</value>
      <webElementGuid>2ec000b4-9224-4e62-9d8c-02c0dd550529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>8177cf9b-cc92-406d-89f7-a60334f6d757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Testing Status</value>
      <webElementGuid>cdf74ac5-58eb-491b-9b97-799f46633097</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_30_list&quot;)/li[@class=&quot;p-ripple p-element p-autocomplete-item ng-tns-c329-52 ng-star-inserted&quot;]</value>
      <webElementGuid>0aba61f9-cdb9-4803-a93c-6c4ff7200062</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='']</value>
      <webElementGuid>9882d646-7746-4683-a115-c90fdf73754e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='pr_id_30_list']/li</value>
      <webElementGuid>1546f7e4-2b32-456c-b764-8d2d9d3738f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/ul/li</value>
      <webElementGuid>2a32c860-8d61-4591-8400-d94f61ac2dd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Testing Status' or . = 'Testing Status')]</value>
      <webElementGuid>ddc1b5d4-4c2e-40ef-9a66-00a750d34e5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
