<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Update</name>
   <tag></tag>
   <elementGuidId>e2beb5a2-2a7e-4ddc-9ee9-64db2a188dce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='dialog-save']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dialog-save</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>18becfac-2edb-4d09-aae9-a619744bca0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dialog-save</value>
      <webElementGuid>28a3a3e1-d805-481c-879a-741826a1176d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>f67de8b9-ab26-4eae-85f1-a0ee9c27cf3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>d4e7d71b-3f46-43b8-9ae2-d4e99b038942</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-focus-indicator mat-flat-button mat-button-base mat-primary cdk-focused cdk-mouse-focused</value>
      <webElementGuid>232aa54d-ddee-4b6d-94b8-073122103053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-color</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>e4454752-e681-4eaa-a25d-3ec8f151a155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Update </value>
      <webElementGuid>99702c1b-3e42-4a61-8fd7-6ca209412393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dialog-save&quot;)</value>
      <webElementGuid>dc50686d-0785-416d-b273-2dd4421dd702</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='dialog-save']</value>
      <webElementGuid>ed5ed1e6-0af6-4307-a4ba-a454e16de7f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-1']/qmt-job-level-drs-modal/mat-dialog-content/form/mat-dialog-actions/div/button[2]</value>
      <webElementGuid>a4354486-5723-4ac0-a451-cc452db4eb47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-dialog-actions/div/button[2]</value>
      <webElementGuid>554aeea0-46ff-4101-8bbc-b9a29dfa7d69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'dialog-save' and @type = 'submit' and (text() = ' Update ' or . = ' Update ')]</value>
      <webElementGuid>0490f581-dff9-4114-82c7-2588b5a32042</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
