<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_logoutLogout</name>
   <tag></tag>
   <elementGuidId>8b50ad99-3fd1-490c-a3c8-0ff02801c75a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.mat-focus-indicator.mat-menu-item.ng-tns-c139-2.cdk-focused.cdk-mouse-focused</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mat-menu-panel-0']/div/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>63d61d8a-1c13-4074-a979-40857ff35795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-focus-indicator mat-menu-item ng-tns-c139-2 cdk-focused cdk-mouse-focused</value>
      <webElementGuid>94a45cc5-4dfe-4470-9057-a8ac46427655</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>043d6a0c-935a-46fa-95e3-1a74bef6efb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5e59549b-e711-4911-80a7-e7dc03e984ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c9c908fb-98ee-4ca4-bf6e-825a73b42760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>logoutLogout</value>
      <webElementGuid>034efb4f-de23-4bc4-90b3-d5189e3e4e3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-menu-panel-0&quot;)/div[@class=&quot;mat-menu-content ng-tns-c139-2&quot;]/button[@class=&quot;mat-focus-indicator mat-menu-item ng-tns-c139-2 cdk-focused cdk-mouse-focused&quot;]</value>
      <webElementGuid>f7e770e7-dc45-4bf5-9107-4f78a9dcf068</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mat-menu-panel-0']/div/button[2]</value>
      <webElementGuid>f9ac1121-b267-4809-93b4-38663034ea7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account Settings'])[1]/following::button[1]</value>
      <webElementGuid>56c377dd-abe5-48ff-acac-e147e7738d9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 2 to 2 of 2 entries'])[1]/following::button[8]</value>
      <webElementGuid>d3cdf80a-6ae1-4385-b23b-d27830761b5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/button[2]</value>
      <webElementGuid>90a653ea-193c-4cf5-872d-3c6f4092ae1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'logoutLogout' or . = 'logoutLogout')]</value>
      <webElementGuid>2ccce5a8-fa61-4feb-93dc-158488f6e0e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
