<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_10_1</name>
   <tag></tag>
   <elementGuidId>d2775d30-58ac-4e51-8e7b-9831629ca5c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '10' or . = '10')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pr_id_7_label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='pr_id_7_label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ef157b4c-72b4-4dcd-bec0-b37f4d1e7cd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-element ng-tns-c156-49 p-dropdown-label p-inputtext ng-star-inserted</value>
      <webElementGuid>cdd1c65e-af22-4630-a187-8a52aab60549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pr_id_7_label</value>
      <webElementGuid>52186362-cd34-4398-ac25-563cdaa7b47d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>1a70e2e5-c679-4d54-a2fe-f98f9baa3662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_7_label&quot;)</value>
      <webElementGuid>1175804a-67c8-482c-8d32-29a7ca81b82c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='pr_id_7_label']</value>
      <webElementGuid>ffcbca50-31d4-437a-9314-ac7e72e73dcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_6']/p-paginator/div/p-dropdown/div/span</value>
      <webElementGuid>e5c9b0ad-ecc1-451e-b990-36ae25c6e091</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 1 to 2 of 2 entries'])[1]/following::span[6]</value>
      <webElementGuid>776d9e83-3371-4bee-b4ba-60e94ca14dc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='new category'])[1]/following::span[13]</value>
      <webElementGuid>5371a98a-fd28-449d-89d1-2af7ff5ab1b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'pr_id_7_label', '&quot;', ')')])[1]/preceding::span[2]</value>
      <webElementGuid>c6cc2901-cef2-4146-8917-ca0d5618defe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='10']/parent::*</value>
      <webElementGuid>eb4f7209-82b1-4568-9b7e-dc521711a2d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-dropdown/div/span</value>
      <webElementGuid>1cc822b9-dbba-4a6e-b1fd-872f03fd826b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'pr_id_7_label' and (text() = '10' or . = '10')]</value>
      <webElementGuid>6552989a-c904-479f-afc3-77ce89056a6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
