<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_10_1_2</name>
   <tag></tag>
   <elementGuidId>b3cdbee3-ab31-41ab-9781-0e812a617cd4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '10' or . = '10')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pr_id_9_label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='pr_id_9_label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>88b444bf-1092-4346-989b-e77b18e36049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-element ng-tns-c156-57 p-dropdown-label p-inputtext ng-star-inserted</value>
      <webElementGuid>c58abd08-c4fc-4434-95ca-84c076c63631</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pr_id_9_label</value>
      <webElementGuid>bc077c7b-3b7a-41e2-9439-f1ab80c5be69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>c2377d00-1040-4d70-ace9-7e5b452061d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_9_label&quot;)</value>
      <webElementGuid>9fe6400d-f56c-4ff2-88be-c7bf71f548b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='pr_id_9_label']</value>
      <webElementGuid>271fc03e-2c43-485a-ae7e-95ce34e501a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_8']/p-paginator/div/p-dropdown/div/span</value>
      <webElementGuid>636e4d49-cfe2-4849-8c39-8cefa4075fb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 1 to 2 of 2 entries'])[1]/following::span[6]</value>
      <webElementGuid>895a2840-f247-4cda-9794-4bc366bd6c55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inactive'])[1]/following::span[13]</value>
      <webElementGuid>033ac6d4-16b2-4c5c-9686-f35f1d3eac37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'pr_id_9_label', '&quot;', ')')])[1]/preceding::span[2]</value>
      <webElementGuid>a4b0c153-85f7-418d-b43e-178ee97bbbc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='10']/parent::*</value>
      <webElementGuid>205368b9-ef6d-4d47-bc0a-ce03e21fa446</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-dropdown/div/span</value>
      <webElementGuid>e3755826-a4fa-4b14-a55b-347e3ba1d69c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'pr_id_9_label' and (text() = '10' or . = '10')]</value>
      <webElementGuid>7058bd39-70c8-41d1-9636-46782d6fa541</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
