<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textareaNote</name>
   <tag></tag>
   <elementGuidId>29a98213-44cb-4c9d-96fc-d74822f4f80f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='Note']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Note</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>b3b18e41-7235-4125-a3d5-ed0f2aba2f78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-element p-inputtextarea !w-full p-inputtext-sm ng-untouched ng-valid p-filled</value>
      <webElementGuid>15a8f655-4f86-4667-bebd-0c7df4c8e741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Note</value>
      <webElementGuid>51eaf138-a2f3-4c3f-b0c9-98c94359eb50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-form</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>e4a0b2d7-04dd-4ea0-8b2a-bf3aa7327af3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>019ebe5f-c064-4e12-a986-c944c06aa11c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>cc568e70-675f-45c0-a0c8-7cd77e286e1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-auto-resize</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5b11b8af-f442-4cd9-a288-c0da7c95fb47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-is-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>98bd37ef-0914-4178-8640-e8d20c2dc72a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Note&quot;)</value>
      <webElementGuid>d3ad7de6-eccd-40e5-bf13-f0cd83c7d89b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='Note']</value>
      <webElementGuid>5aa54dcf-2149-4d07-ace4-0d03d0f8f5ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>f728dd4b-05c2-47d6-bfe6-8506cd61b978</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'Note']</value>
      <webElementGuid>071318b2-14ed-460b-acf2-ebab0b1cc960</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
