<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputProject Number</name>
   <tag></tag>
   <elementGuidId>673d7b26-ae21-4265-8609-0fe611f0665a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Project Number']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a6cb501b-c6b2-4fd6-8275-c87405e73559</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-element !w-full p-inputtext-sm ng-untouched ng-pristine</value>
      <webElementGuid>3c26ffb7-626d-45a4-9b89-a58383fa6321</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Project Number</value>
      <webElementGuid>1e0d90c0-7462-437d-b097-41aa43932039</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>09fc43fe-175e-413e-aa89-dedec1a763b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-form</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>d2e3bfbe-a07d-454e-8829-06fa8c7ea712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>undefined</value>
      <webElementGuid>1b697e27-9c31-4b98-888f-c4b2cbb2b2db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>undefined</value>
      <webElementGuid>2ee1209f-ed52-4171-a7b6-e91fce9dd451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Project Number&quot;)</value>
      <webElementGuid>50c2133d-ae55-4b00-907b-132943920700</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Project Number']</value>
      <webElementGuid>74e155ae-8479-4fba-8f33-fd1f6f0e7bc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//qmt-new-input/div/input</value>
      <webElementGuid>6f243165-bde9-4eb4-a8e6-311046098c46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Project Number' and @type = 'text']</value>
      <webElementGuid>0437f75a-b237-4cde-88aa-62a566ffccd6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
