<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_101  Richmond BC</name>
   <tag></tag>
   <elementGuidId>96375905-b560-4701-aad3-6fc232cdcdcd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//li[@id=''])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>5229b13b-968f-4aa1-a277-f11e61c3e5d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>0cc18e0a-2bf7-47d0-a366-63691836ea5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-ripple p-element p-autocomplete-item ng-tns-c329-68 ng-star-inserted</value>
      <webElementGuid>1c2eb95a-d398-4326-812c-afb9a3cfcd93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>c77f4c77-397f-4d01-8989-82d1862d15dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>101 | Richmond BC </value>
      <webElementGuid>25eeab42-cd87-44c3-ba2d-2860039a3720</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_38_list&quot;)/li[@class=&quot;p-ripple p-element p-autocomplete-item ng-tns-c329-68 ng-star-inserted&quot;]</value>
      <webElementGuid>1e634bf1-0b18-4724-aaf0-c49ed9b9bea3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//li[@id=''])[2]</value>
      <webElementGuid>4052e7e8-65f1-421c-950c-57bd1fa4740d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='pr_id_38_list']/li[2]</value>
      <webElementGuid>c65507d9-0a7d-4f16-a957-9be28c72405f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[2]</value>
      <webElementGuid>78af1877-b6c4-47cc-8fdf-b9238c0b6b8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '101 | Richmond BC ' or . = '101 | Richmond BC ')]</value>
      <webElementGuid>e3723d24-655c-4006-8c38-4ec70eef5024</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
