<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Emp 5  emp5gmail.com</name>
   <tag></tag>
   <elementGuidId>9b6a3a4d-497c-44b6-8a36-0245d5a373d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.p-ripple.p-element.p-autocomplete-item.ng-tns-c329-55.ng-star-inserted</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Emp 5 | emp5@gmail.com' or . = 'Emp 5 | emp5@gmail.com')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>d60cd935-b434-4ed0-9ab2-742a2cc5cd93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>b604c49e-7b80-461f-8339-e7fd8813eb92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-ripple p-element p-autocomplete-item ng-tns-c329-55 ng-star-inserted</value>
      <webElementGuid>3d525a18-e344-4d6b-b916-dbe30c68e762</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>d0c4ecf8-0bfc-41c8-96ab-d60d7a2909e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Emp 5 | emp5@gmail.com</value>
      <webElementGuid>8ebd66db-8426-4755-b1b5-6c186f5a8dc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_25_list&quot;)/li[@class=&quot;p-ripple p-element p-autocomplete-item ng-tns-c329-55 ng-star-inserted&quot;]</value>
      <webElementGuid>206e8158-1720-4985-9043-3743cd2eafcc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='']</value>
      <webElementGuid>00c34dae-5570-4f9e-bc5b-a20ae31e6617</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='pr_id_25_list']/li</value>
      <webElementGuid>e88a5d4b-a2b6-4b8d-8020-8773cee3286d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li</value>
      <webElementGuid>c9632950-94a0-431e-a08b-0c6afc1abbdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Emp 5 | emp5@gmail.com' or . = 'Emp 5 | emp5@gmail.com')]</value>
      <webElementGuid>13e3b163-585e-4962-9115-fe41dd4aa165</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
