<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Shanta Paul  shanta.paulqm.com</name>
   <tag></tag>
   <elementGuidId>8ac119ba-3eaf-4412-bc72-6ae66499ab6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.p-ripple.p-element.p-autocomplete-item.ng-tns-c329-54.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>3c95aaa5-b12f-458e-a76e-24eeef59e28b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>0a47bb4a-d96e-428a-95fd-2cefa5f97c39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-ripple p-element p-autocomplete-item ng-tns-c329-54 ng-star-inserted</value>
      <webElementGuid>5c152cce-7c04-4a75-a5d7-8b5ce7ba3886</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>20f64ef1-848e-40a3-8b33-2b69e5d36fb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Shanta Paul | shanta.paul@qm.com</value>
      <webElementGuid>0466db27-9197-431d-afbc-dc06659d90b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_24_list&quot;)/li[@class=&quot;p-ripple p-element p-autocomplete-item ng-tns-c329-54 ng-star-inserted&quot;]</value>
      <webElementGuid>8aa790ec-fad8-4dc3-878f-1066835b1a4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='']</value>
      <webElementGuid>b0b96d09-b354-4cca-b0fc-27c6a3acd7a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='pr_id_24_list']/li</value>
      <webElementGuid>ccea69b5-a150-4ffa-a98c-930fa4236ead</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li</value>
      <webElementGuid>e9c1724a-9dc8-44a1-b193-9b528195e24d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Shanta Paul | shanta.paul@qm.com' or . = 'Shanta Paul | shanta.paul@qm.com')]</value>
      <webElementGuid>1294957b-802e-472a-bb23-093be667890d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
