<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>default_value_check_box</name>
   <tag></tag>
   <elementGuidId>20204fb5-3a9b-4654-9775-5ab10225f261</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'default-value-checkbox']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-checkbox[@id='mat-checkbox-6']/label/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-checkbox-6 > label.mat-checkbox-layout > span.mat-checkbox-inner-container.mat-checkbox-inner-container-no-side-margin</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f04e8a44-d2c2-4d64-9bf2-90e126538acd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-checkbox-inner-container mat-checkbox-inner-container-no-side-margin</value>
      <webElementGuid>6e0676d2-6f04-48e8-9c84-9dfec5b4b545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[2]/div[2]/div[1]/mat-dialog-container[1]/qmt-custom-fleet-field-model[1]/mat-dialog-content[1]/form[1]/div[2]/div[1]/div[1]/mat-checkbox[1]/label[1]/span[1]</value>
      <webElementGuid>4d881815-c4a5-4d5e-a645-71266ab5ec1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>default-value-checkbox</value>
      <webElementGuid>0dcacec3-2b06-47b4-900d-74dc841db492</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-checkbox[@id='mat-checkbox-6']/label/span</value>
      <webElementGuid>164049f5-04ca-4dfa-b419-03aff117fee3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/mat-checkbox/label/span</value>
      <webElementGuid>1d29c3f6-8dbf-48e9-ace6-9f66b179848f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
