<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_checkbox</name>
   <tag></tag>
   <elementGuidId>e4666dae-fb1c-4e46-9e52-075615e6dbe8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'checkbox']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-dialog-container[@id='mat-dialog-3']/qmt-custom-fleet-field-model/mat-dialog-content/form/div/div/div[4]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>147a7b5f-4f8b-4fcf-b2e0-db1a5d531818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-2 flex justify-center items-center border rounded-md h-[80px] bg-[#B6D1F71F] border-dashed</value>
      <webElementGuid>4dbe05fc-2ad4-4762-b2d3-4295e5c2fc32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>bg-[#B6D1F71F] border-dashed</value>
      <webElementGuid>be66ab23-17a1-45b5-a619-9d0bd0ddffda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> </value>
      <webElementGuid>0b49c61a-3a60-4b82-a3e3-e666a628af5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@dir='ltr']//div[4]//div[1]</value>
      <webElementGuid>8d7b9303-6a5e-42d6-a428-4b1362d6e350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>10c68706-af60-41bb-bfb7-067c78906474</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-3']/qmt-custom-fleet-field-model/mat-dialog-content/form/div/div/div[4]/div</value>
      <webElementGuid>1191ec49-5d88-4643-b90a-af4548df1bc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[4]/div</value>
      <webElementGuid>b78c1eeb-4991-4e60-b993-3b2f48fbce9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' ' or . = ' ')]</value>
      <webElementGuid>3eb1ed79-1124-483a-84b9-513113a96587</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
