<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Date Time</name>
   <tag></tag>
   <elementGuidId>da58fde2-bc92-47ae-8efc-c4edebc6ceaf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-dialog-container[@id='mat-dialog-6']/qmt-custom-fleet-field-model/mat-dialog-content/form/div/div/div[6]/div/h4</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//h4[normalize-space()='Date Time']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>8d3586e1-2a56-49bf-be88-d07a2d0000d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>!m-0 ng-star-inserted</value>
      <webElementGuid>3d40db23-0147-4f1d-b6d7-17305dfe55d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Date Time</value>
      <webElementGuid>e39b6576-385c-4db3-81a5-0669310a4783</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//h4[normalize-space()='Date Time']</value>
      <webElementGuid>f391c2d0-d04d-47c0-b06d-d8fab31127c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-6']/qmt-custom-fleet-field-model/mat-dialog-content/form/div/div/div[6]/div/h4</value>
      <webElementGuid>2aa35d74-3988-40c3-b8aa-2b3200ffd025</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/h4</value>
      <webElementGuid>98094a33-b0c0-4e9b-a58f-cdaf2b50404b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'Date Time' or . = 'Date Time')]</value>
      <webElementGuid>581fc2b2-b836-40a0-be9e-5b57b853500d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
