<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textareaNote 2</name>
   <tag></tag>
   <elementGuidId>5f15c312-e45c-4785-ae7b-719fcd962823</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='Note 2']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html[1]/body[1]/qm-root[1]/qmt-layout[1]/qmt-navigation[1]/mat-sidenav-container[1]/mat-sidenav-content[1]/div[1]/div[1]/qmt-union-code-form[1]/form[1]/div[1]/div[2]/div[2]/div[1]/div[1]/qmt-textarea-input[2]/div[1]/mat-form-field[1]/div[1]/div[1]/div[3]/textarea[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>f7a26191-a1a8-4ddd-a8f3-ccb9aed20bf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control text-sm text-[#91919180] font-medium ng-tns-c99-43 ng-untouched ng-valid cdk-text-field-autofill-monitored ng-dirty</value>
      <webElementGuid>26df45bf-687d-48d3-8587-b9d1734de256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-id</name>
      <type>Main</type>
      <value>Note 2</value>
      <webElementGuid>00535d42-53c6-4f24-b214-d08e159a6033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-model</name>
      <type>Main</type>
      <value>N</value>
      <webElementGuid>170978c7-7fce-4b45-8da6-459ee827caa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>10d5ab7f-09cc-4093-9d32-fc7965c5d1eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Note 2</value>
      <webElementGuid>2a73b9e8-1ea3-463d-960a-f6e2d8338c31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>873727f6-4615-4274-8360-c99c2271cdf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e2c16723-bad6-4450-aa13-f40228a920a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/qm-root[1]/qmt-layout[1]/qmt-navigation[1]/mat-sidenav-container[1]/mat-sidenav-content[1]/div[1]/div[1]/qmt-union-code-form[1]/form[1]/div[1]/div[2]/div[2]/div[1]/div[1]/qmt-textarea-input[2]/div[1]/mat-form-field[1]/div[1]/div[1]/div[3]/textarea[1]</value>
      <webElementGuid>b657538b-3ed2-471c-aee6-f1adad1bee21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='Note 2']</value>
      <webElementGuid>2d29acdc-3f54-458d-8588-2fd99eac355a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//qmt-textarea-input[2]/div/mat-form-field/div/div/div[3]/textarea</value>
      <webElementGuid>70dcdcfd-a4ef-4c91-aec7-7d4cdb4aa581</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'Note 2']</value>
      <webElementGuid>a6fc8d6a-68fa-4221-b38f-c22678749e6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
