<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_AMOUNT</name>
   <tag></tag>
   <elementGuidId>fb7fa47f-0f8d-4cc3-bce1-8bd4f58f26d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.p-ripple.p-element.p-autocomplete-item.ng-tns-c329-40.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>121d2f48-5ee1-4941-8c3e-c7d1241878fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>35c135ab-72dc-4106-ae53-14cad49421e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-ripple p-element p-autocomplete-item ng-tns-c329-40 ng-star-inserted</value>
      <webElementGuid>1d160f4f-9d68-4eb5-a448-39ed551ddd41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>e1251c47-223d-41b9-88f6-ffa97c076648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AMOUNT</value>
      <webElementGuid>f764328f-6ac8-4bec-9881-58f31cfce961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_6_list&quot;)/li[@class=&quot;p-ripple p-element p-autocomplete-item ng-tns-c329-40 ng-star-inserted&quot;]</value>
      <webElementGuid>9d36bed3-a263-493e-b143-430aef433b30</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='']</value>
      <webElementGuid>998ce1b2-36fc-412b-be08-1fbec9fba429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='pr_id_6_list']/li</value>
      <webElementGuid>bdd72bb2-07a8-4ccb-98c2-8b5006058b50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/li</value>
      <webElementGuid>fb4d877b-4892-4f99-8a06-03ca2f5ffda0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'AMOUNT' or . = 'AMOUNT')]</value>
      <webElementGuid>d89dd73e-074d-4b89-a1ae-f9645f0e9ff6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
