<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-icon_keyboard_arrow_down</name>
   <tag></tag>
   <elementGuidId>1eefab7e-96a0-4011-9310-71b723789fc6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/mat-icon</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>mat-icon.mat-icon.notranslate.ng-tns-c177-17.ng-trigger.ng-trigger-ExpandedLTR.material-icons.mat-icon-no-color.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-icon</value>
      <webElementGuid>d5617e23-86f1-4c27-b315-4f431b7d6250</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9daa4055-14b7-4b74-830f-fc2011c25e33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-icon notranslate ng-tns-c177-17 ng-trigger ng-trigger-ExpandedLTR material-icons mat-icon-no-color ng-star-inserted</value>
      <webElementGuid>e9745210-a354-463c-abe3-ceea34fd8ff9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>06d018c6-f9e6-4e27-8c6e-2dbd0bd2f25d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-type</name>
      <type>Main</type>
      <value>font</value>
      <webElementGuid>9a4fad49-0c33-4e26-8826-9803c88e02f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> keyboard_arrow_down </value>
      <webElementGuid>196f4810-e33c-414e-8358-f384f898b493</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography mat-app-background&quot;]/qm-root[1]/qmt-layout[@class=&quot;ng-star-inserted&quot;]/qmt-navigation[1]/mat-sidenav-container[@class=&quot;mat-drawer-container mat-sidenav-container sidenav-container&quot;]/mat-sidenav[@class=&quot;mat-drawer mat-sidenav sidenav relative ng-tns-c183-1 ng-trigger ng-trigger-transform mat-drawer-side mat-drawer-opened mat-sidenav-fixed ng-star-inserted&quot;]/div[@class=&quot;mat-drawer-inner-container ng-tns-c183-1&quot;]/ng-material-multilevel-menu[@class=&quot;ng-tns-c183-1&quot;]/div[@class=&quot;amml-container my-custom-class normal-case ng-star-inserted&quot;]/mat-list[@class=&quot;mat-list mat-list-base&quot;]/ng-list-item[@class=&quot;ng-tns-c177-17 ng-star-inserted&quot;]/div[@class=&quot;amml-menu-container ng-tns-c177-17&quot;]/mat-list-item[@class=&quot;mat-list-item mat-focus-indicator mat-ripple ng-tns-c177-17 amml-item selected-amml-item level-1-submenulevel-0 ng-star-inserted&quot;]/span[@class=&quot;mat-list-item-content&quot;]/a[@class=&quot;anml-link ng-tns-c177-17 ng-star-inserted&quot;]/div[@class=&quot;amml-icon-arrow-container ng-tns-c177-17 ng-star-inserted&quot;]/mat-icon[@class=&quot;mat-icon notranslate ng-tns-c177-17 ng-trigger ng-trigger-ExpandedLTR material-icons mat-icon-no-color ng-star-inserted&quot;]</value>
      <webElementGuid>ddd97f2e-cc6f-4c69-87ac-712140ccd4f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/mat-icon</value>
      <webElementGuid>50af135d-5bb6-4b66-97ab-0d4d398b4aef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-icon[(text() = ' keyboard_arrow_down ' or . = ' keyboard_arrow_down ')]</value>
      <webElementGuid>7328d975-b78e-4154-ac11-5eae8d841c05</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
