<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textareaNote 1</name>
   <tag></tag>
   <elementGuidId>f4d552c9-7038-4e0a-a939-853b1b970d3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='Note 1']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html[1]/body[1]/qm-root[1]/qmt-layout[1]/qmt-navigation[1]/mat-sidenav-container[1]/mat-sidenav-content[1]/div[1]/div[1]/qmt-union-code-form[1]/form[1]/div[1]/div[2]/div[3]/div[1]/div[1]/qmt-textarea-input[1]/div[1]/mat-form-field[1]/div[1]/div[1]/div[3]/textarea[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>0c94241f-289e-4427-b2ad-de2d4a5190a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control text-sm text-[#91919180] font-medium ng-tns-c99-42 ng-untouched ng-valid cdk-text-field-autofill-monitored ng-dirty</value>
      <webElementGuid>1cdeca92-676b-49d4-84ca-30ad9f511a82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-id</name>
      <type>Main</type>
      <value>Note 1</value>
      <webElementGuid>2de86844-bf18-4d2f-8e9d-171027e078d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-model</name>
      <type>Main</type>
      <value>N</value>
      <webElementGuid>a0df6e88-3242-4627-af4c-863cfd7ac5d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9added70-3d37-4a90-9d6e-a4e753b813ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Note 1</value>
      <webElementGuid>502ec498-749f-4226-a1b8-5cf5aa84299f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a0a32aaa-254a-4b08-9642-b503f7de1ad9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fb9fed34-e78a-4dff-adfa-33958b4e3bb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/qm-root[1]/qmt-layout[1]/qmt-navigation[1]/mat-sidenav-container[1]/mat-sidenav-content[1]/div[1]/div[1]/qmt-union-code-form[1]/form[1]/div[1]/div[2]/div[3]/div[1]/div[1]/qmt-textarea-input[1]/div[1]/mat-form-field[1]/div[1]/div[1]/div[3]/textarea[1]</value>
      <webElementGuid>440cf152-f4f2-46cf-8907-4bd8324087c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='Note 1']</value>
      <webElementGuid>de2c2b1f-e278-4099-9609-dbdc102670ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>32fcb204-d887-4b44-90d6-12782c10f209</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'Note 1']</value>
      <webElementGuid>9e5af224-dc0b-4803-b0c8-c1fa7d4cc9fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
