<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_p-inputtext p-component p-element w-f_006ace</name>
   <tag></tag>
   <elementGuidId>5fb299ae-8cf5-4270-8c94-644c610e7643</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>_ngcontent-trs-c201</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>input[class='p-inputtext p-component p-element !w-full p-inputtext-sm ng-pristine ng-invalid ng-dirty ng-touched']&#xd;
</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>af8cb78c-8dc7-4a26-a632-6179041b40c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-element !w-full p-inputtext-sm ng-untouched ng-pristine</value>
      <webElementGuid>bebc2487-396a-41bf-9ebc-cdec40014965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c65c5c90-a45f-43e7-b4db-a8325204aaf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>undefined</value>
      <webElementGuid>7e0ea88d-fb68-4e7d-842e-603e53617243</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>undefined</value>
      <webElementGuid>63b01fbc-004f-4976-945f-1daea2688534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>input[class='p-inputtext p-component p-element !w-full p-inputtext-sm ng-pristine ng-invalid ng-dirty ng-touched']&#xd;
</value>
      <webElementGuid>e0046f76-47d9-41c3-8b9c-efa4ebd1f2f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[3]</value>
      <webElementGuid>661192b1-4755-4cfb-806e-d8c46db42358</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-0']/qmt-base-uom-modal/mat-dialog-content/form/div/qmt-new-input/div/input</value>
      <webElementGuid>b949d857-bcfa-42be-8e8a-9048a29bb62a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//qmt-new-input/div/input</value>
      <webElementGuid>f864712f-d780-43b0-8a6f-997fa6f1802a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>deacd919-c833-457e-a2d3-917aa278e089</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
