<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>click_unit</name>
   <tag></tag>
   <elementGuidId>05e834be-2d32-4ee2-8a78-b99f3c83e0d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html[1]/body[1]/qm-root[1]/qmt-layout[1]/qmt-navigation[1]/mat-sidenav-container[1]/mat-sidenav-content[1]/div[1]/div[1]/qmt-union-code-form[1]/form[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/p-accordion[1]/div[1]/qmt-accordion[1]/p-accordiontab[1]/div[1]/div[2]/div[1]/div[1]/qmt-new-autocomplete[2]/div[1]/p-autocomplete[1]/span[1]/input[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/qm-root[1]/qmt-layout[1]/qmt-navigation[1]/mat-sidenav-container[1]/mat-sidenav-content[1]/div[1]/div[1]/qmt-union-code-form[1]/form[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/p-accordion[1]/div[1]/qmt-accordion[1]/p-accordiontab[1]/div[1]/div[2]/div[1]/div[1]/qmt-new-autocomplete[2]/div[1]/p-autocomplete[1]/span[1]/input[1]</value>
      <webElementGuid>acb5993a-fdc6-484b-905e-bfe3ed3bdb2c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
