<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_amount</name>
   <tag></tag>
   <elementGuidId>115e7074-67b1-4798-af7a-32032dbada44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html[1]/body[1]/qm-root[1]/qmt-layout[1]/qmt-navigation[1]/mat-sidenav-container[1]/mat-sidenav-content[1]/div[1]/div[1]/qmt-union-code-form[1]/form[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/p-accordion[1]/div[1]/qmt-accordion[1]/p-accordiontab[1]/div[1]/div[2]/div[1]/div[1]/qmt-new-input[2]/div[1]/input[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/qm-root[1]/qmt-layout[1]/qmt-navigation[1]/mat-sidenav-container[1]/mat-sidenav-content[1]/div[1]/div[1]/qmt-union-code-form[1]/form[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/p-accordion[1]/div[1]/qmt-accordion[1]/p-accordiontab[1]/div[1]/div[2]/div[1]/div[1]/qmt-new-input[2]/div[1]/input[1]</value>
      <webElementGuid>0a0eab7b-736e-47c4-bb88-d20b8aed6d90</webElementGuid>
   </webElementProperties>
</WebElementEntity>
