<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_name</name>
   <tag></tag>
   <elementGuidId>90d4b3ae-f5c9-4f4f-a46f-5e0b3f91610a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html[1]/body[1]/qm-root[1]/qmt-layout[1]/qmt-navigation[1]/mat-sidenav-container[1]/mat-sidenav-content[1]/div[1]/div[1]/qmt-union-code-form[1]/form[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/p-accordion[1]/div[1]/qmt-accordion[1]/p-accordiontab[1]/div[1]/div[2]/div[1]/div[1]/qmt-new-input[1]/div[1]/input[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/qm-root[1]/qmt-layout[1]/qmt-navigation[1]/mat-sidenav-container[1]/mat-sidenav-content[1]/div[1]/div[1]/qmt-union-code-form[1]/form[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/p-accordion[1]/div[1]/qmt-accordion[1]/p-accordiontab[1]/div[1]/div[2]/div[1]/div[1]/qmt-new-input[1]/div[1]/input[1]</value>
      <webElementGuid>8e34057a-0e4c-4992-bbf7-3949f47cea10</webElementGuid>
   </webElementProperties>
</WebElementEntity>
