<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Delete</name>
   <tag></tag>
   <elementGuidId>d4226fb9-51db-499c-a5ff-b9fede2cec63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='dialog-save']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dialog-save</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c13cd9a8-681d-49c5-aa0c-d466541f7335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dialog-save</value>
      <webElementGuid>e0b85f43-d89e-4815-b511-5caa7961cacb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>50685c5e-6905-479a-bc68-1976d6c864f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-focus-indicator mat-flat-button mat-button-base mat-primary cdk-focused cdk-mouse-focused</value>
      <webElementGuid>8efea7b7-e816-4c3f-acda-aeb1db7c6181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-color</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>95a8edc6-8b3b-434f-b326-71dbc3e86406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Delete </value>
      <webElementGuid>b4c1f151-5686-47e3-b378-2da3a54c8c4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dialog-save&quot;)</value>
      <webElementGuid>3a67b869-728f-4db9-bdbb-ab78e76cd70b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='dialog-save']</value>
      <webElementGuid>de137ccf-19bb-4356-9212-e52a1c4ae7b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-3']/qmt-delete/mat-dialog-actions/div/button[2]</value>
      <webElementGuid>831231b3-b518-40d6-a3f7-2befc45a073d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-dialog-actions/div/button[2]</value>
      <webElementGuid>26eb7ae9-bf02-45fd-9ae8-0fb25834d1f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'dialog-save' and (text() = ' Delete ' or . = ' Delete ')]</value>
      <webElementGuid>e4eb543f-7a60-4c18-a09a-3cf1e20ad9cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
