<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_construction</name>
   <tag></tag>
   <elementGuidId>95aca7b2-6382-421b-81ca-a5bf87c44c8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fleet</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='fleet']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>457e4ab7-c95c-456b-ba8a-be611d834a95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-2 flex justify-center items-center border rounded-md h-[80px] bg-[#B6D1F71F] border-dashed</value>
      <webElementGuid>1fc61b6d-e249-4dd6-b77a-fa8ad727b8ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>bg-[#B6D1F71F] border-dashed</value>
      <webElementGuid>dcf3de25-8ef6-461d-a7c5-5443b3c042d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>construction</value>
      <webElementGuid>bf60f289-885f-4fcf-9eca-52241aa29bdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fleet&quot;)</value>
      <webElementGuid>efd5c2ee-afcd-43c6-afba-f5120142cb37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fleet</value>
      <webElementGuid>4c65276a-b300-41da-9636-aed3f695e59c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='fleet']</value>
      <webElementGuid>0ee92734-1455-45a1-be9c-3e97a67624e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-1']/qmt-job-resource-list-modal/mat-dialog-content/form/div/div/div[2]/div</value>
      <webElementGuid>23a83386-e815-407f-af6d-5ccf39075179</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div[2]/div</value>
      <webElementGuid>1733f0fe-2cb6-48b6-ba0d-0023d3217012</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'fleet' and (text() = 'construction' or . = 'construction')]</value>
      <webElementGuid>4e4af168-5f42-4a84-9adf-59a1f822ad5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-0']/qmt-job-resource-list-modal/mat-dialog-content/form/div/div/div[2]/div</value>
      <webElementGuid>235888b2-3a93-406b-9281-c6fdc21f7eed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'construction' or . = 'construction')]</value>
      <webElementGuid>050a407f-dedf-44f4-8f86-4bb7a32b19cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
