<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Country</name>
   <tag></tag>
   <elementGuidId>c8c5681d-cc6f-4ff9-8c12-e64aed77c375</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>qmt-new-autocomplete > div.field</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//qmt-new-autocomplete/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cd2b2f58-f82f-41db-9562-8219ed102439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field</value>
      <webElementGuid>97a0c217-a1c3-4bbe-bfe9-ab9d01c66788</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Country* </value>
      <webElementGuid>ee1e7137-9aff-4a62-afb8-1653e46831a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography mat-app-background&quot;]/qm-root[1]/qmt-layout[@class=&quot;ng-star-inserted&quot;]/qmt-navigation[1]/mat-sidenav-container[@class=&quot;mat-drawer-container mat-sidenav-container sidenav-container&quot;]/mat-sidenav-content[@class=&quot;mat-drawer-content mat-sidenav-content&quot;]/div[@class=&quot;overflow-y-auto p-6 min-h-[calc(100%_-_80px)] bg-[#F2F2F2]&quot;]/div[@class=&quot;bg-white rounded-lg py-7 px-9 h-full&quot;]/qmt-global-user-form[@class=&quot;ng-star-inserted&quot;]/form[@class=&quot;ng-pristine ng-invalid ng-touched&quot;]/div[@class=&quot;mt-16&quot;]/div[@class=&quot;grid grid-cols-3 gap-8 mt-5&quot;]/qmt-new-autocomplete[1]/div[@class=&quot;field&quot;]</value>
      <webElementGuid>a5bb9500-477a-462c-953a-d42c8330aadb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//qmt-new-autocomplete/div</value>
      <webElementGuid>2db19e23-bd2b-46ba-9a3d-1f31d7b83265</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Country* ' or . = 'Country* ')]</value>
      <webElementGuid>5e2bb4b6-fd5f-489d-a25a-838b3db3276a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
