<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Emp 1  emp1gmail.com</name>
   <tag></tag>
   <elementGuidId>56cec357-cd22-438b-b8fd-c3681a161c43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ng-tns-c329-56.ng-star-inserted</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html[1]/body[1]/div[3]/ul[1]/li[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>38b1086e-ee2e-4aca-a21c-73b0cfe2e2ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c329-56 ng-star-inserted</value>
      <webElementGuid>509f7765-9811-4ffe-9451-3dbb7470aeeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Emp 1 | emp1@gmail.com</value>
      <webElementGuid>b3d0d735-f206-4290-bcf3-037f40a0e250</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[3]/ul[1]/li[1]</value>
      <webElementGuid>117ed367-09d8-4176-9509-d267907c7de0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='pr_id_26_list']/li/span</value>
      <webElementGuid>fd4d27f2-8338-400e-aa8e-803d1bbb00bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/span</value>
      <webElementGuid>dac3f937-fb36-42a0-94c0-87cd9ce2057f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Emp 1 | emp1@gmail.com' or . = 'Emp 1 | emp1@gmail.com')]</value>
      <webElementGuid>1ae194f0-2914-4d96-a915-5570171a0bea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
