<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputName</name>
   <tag></tag>
   <elementGuidId>90fc7894-05a4-4a4f-aff6-aacf8e2baa3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='Name'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.pb-6.px-5 > qmt-new-input > div.field.w-full > #Name</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html[1]/body[1]/div[2]/div[4]/div[1]/mat-dialog-container[1]/qmt-sub-job-modal[1]/mat-dialog-content[1]/form[1]/div[1]/qmt-new-input[1]/div[1]/input[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b69cc50e-a4ae-4152-9b21-79c54b660cd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-element !w-full p-inputtext-sm ng-untouched ng-pristine</value>
      <webElementGuid>ec8843d0-8d90-4101-a3d8-43850e222e47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>2a812943-0c3d-43db-bbd7-627032a65faa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>626d1601-63e5-4dc6-89de-61800de8fbea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-form</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>24436e2d-3cf7-4191-9e02-331ed98271b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>undefined</value>
      <webElementGuid>4a3b0375-9230-4dca-aa57-7674254a6e6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>undefined</value>
      <webElementGuid>aa19d6a3-b7ae-4e99-ad76-bd8e0f48bf56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[2]/div[4]/div[1]/mat-dialog-container[1]/qmt-sub-job-modal[1]/mat-dialog-content[1]/form[1]/div[1]/qmt-new-input[1]/div[1]/input[1]</value>
      <webElementGuid>31692955-c4c6-4822-9b2c-1dbd0395f174</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='Name'])[2]</value>
      <webElementGuid>ec4a4bfe-a6ac-44fb-92b2-002f625fbf3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-1']/qmt-sub-job-modal/mat-dialog-content/form/div/qmt-new-input/div/input</value>
      <webElementGuid>a269222c-e3a0-4214-93d4-c96a8c494e2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//qmt-sub-job-modal/mat-dialog-content/form/div/qmt-new-input/div/input</value>
      <webElementGuid>b32bf0c8-e324-47da-b7f6-bede8946c92e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Name' and @type = 'text']</value>
      <webElementGuid>481537db-627a-4fea-b71f-0b38ff292913</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
