<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_mat-checkbox-inner-container_1</name>
   <tag></tag>
   <elementGuidId>335c666b-87c7-438d-a3af-2e030f47d81d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-checkbox[@id='mat-checkbox-3']/label/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html[1]/body[1]/qm-root[1]/qmt-layout[1]/qmt-navigation[1]/mat-sidenav-container[1]/mat-sidenav-content[1]/div[1]/div[1]/qmt-union-code-form[1]/form[1]/div[1]/div[2]/div[9]/div[1]/div[1]/mat-checkbox[2]/label[1]/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-checkbox-3 > label.mat-checkbox-layout > span.mat-checkbox-inner-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fe089b13-d7f4-405b-afa1-452704e8df4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-checkbox-inner-container</value>
      <webElementGuid>6b6e9df1-ec9c-4484-bbd9-09d433e38b16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/qm-root[1]/qmt-layout[1]/qmt-navigation[1]/mat-sidenav-container[1]/mat-sidenav-content[1]/div[1]/div[1]/qmt-union-code-form[1]/form[1]/div[1]/div[2]/div[9]/div[1]/div[1]/mat-checkbox[2]/label[1]/span[2]</value>
      <webElementGuid>1216999c-7d88-419b-b531-add95c61c558</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-checkbox[@id='mat-checkbox-3']/label/span</value>
      <webElementGuid>8f867d6a-3e70-493b-905c-a65d0b76a2ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-checkbox[2]/label/span</value>
      <webElementGuid>a99fc87a-3faf-489b-97dd-f3983244201c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
