<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_103  Emergency Response</name>
   <tag></tag>
   <elementGuidId>ff3a5edc-230a-47b0-ad7f-f6c29b45b350</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//li[@id=''])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>1547f6cf-1d64-45a3-8384-f2d7fdb42f49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>f41b345b-171d-4864-a86e-c20f00a0cccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-ripple p-element p-autocomplete-item ng-tns-c329-41 ng-star-inserted</value>
      <webElementGuid>7fe45d5d-ee1c-45fd-81a6-960d92ec5ca5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>d284c027-31f1-4832-aa29-a5916e5b9062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>103 | Emergency Response </value>
      <webElementGuid>8c176325-b467-4766-bd63-eb393c4ea106</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_16_list&quot;)/li[@class=&quot;p-ripple p-element p-autocomplete-item ng-tns-c329-41 ng-star-inserted&quot;]</value>
      <webElementGuid>5d34779c-b2f6-4261-8c04-e1c8722b3b34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//li[@id=''])[4]</value>
      <webElementGuid>fad26b4d-6ac2-4b7c-b20c-d21aaa0f8562</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='pr_id_16_list']/li[4]</value>
      <webElementGuid>a97b0404-67fa-4395-b121-849a7f9f5fa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]</value>
      <webElementGuid>0b35047c-bfa1-4319-8f60-b4ceeabfd9bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '103 | Emergency Response ' or . = '103 | Emergency Response ')]</value>
      <webElementGuid>d0f2109c-c766-48b4-8e6d-9590ca378022</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
