<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_111  region name</name>
   <tag></tag>
   <elementGuidId>32b9dc1d-6f68-440d-a000-5ba65a60ee2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.p-ripple.p-element.p-autocomplete-item.ng-tns-c329-42.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>1077bd69-417d-475c-b35a-8a659e95a095</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>59f5cff0-a436-453c-89ec-da42dbd18b39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-ripple p-element p-autocomplete-item ng-tns-c329-42 ng-star-inserted</value>
      <webElementGuid>ccf50c35-3401-43dd-92fe-19cdcdf3fef4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>4020e56e-7753-4929-9c26-3c76c7ee026a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>111 | region name </value>
      <webElementGuid>7c90e1c4-1fda-4e78-87eb-e1b2d4397d91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_17_list&quot;)/li[@class=&quot;p-ripple p-element p-autocomplete-item ng-tns-c329-42 ng-star-inserted&quot;]</value>
      <webElementGuid>be8e8e20-da4f-4589-80d4-6db46c4a20f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='']</value>
      <webElementGuid>266a7598-36e7-4f71-9b02-21ae9cfba3d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='pr_id_17_list']/li</value>
      <webElementGuid>a27c7a90-15b3-4797-a50b-31f7ba0df740</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/li</value>
      <webElementGuid>25b7dab5-957b-43d9-95c6-e7ada2a5536f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '111 | region name ' or . = '111 | region name ')]</value>
      <webElementGuid>b3b7a6f6-e0f4-46bd-9ce9-a95e264f8d85</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
