<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>thursday</name>
   <tag></tag>
   <elementGuidId>4f47763c-1c71-4c34-9f4d-0014fecd9e5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#thursday > label.mat-checkbox-layout > span.mat-checkbox-inner-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-checkbox[@id='thursday']/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ebe769d2-d2e7-4067-a167-e215bb6d4b21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-checkbox-inner-container</value>
      <webElementGuid>bca9a39d-8e4d-476d-aa90-3d998ce1ea44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;thursday&quot;)/label[@class=&quot;mat-checkbox-layout&quot;]/span[@class=&quot;mat-checkbox-inner-container&quot;]</value>
      <webElementGuid>d1fb136b-49fe-4e7f-9467-2ee4ae18d82e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-checkbox[@id='thursday']/label/span</value>
      <webElementGuid>dbac880a-710f-4dc8-9081-ad4d75eb68ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-checkbox[4]/label/span</value>
      <webElementGuid>8de67f38-bdcf-4937-bce7-4c43e10cd122</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
