<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>divisioncode</name>
   <tag></tag>
   <elementGuidId>b835bba5-8820-4382-9ae1-6d6652ef9954</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html[1]/body[1]/div[2]/div[2]/div[1]/mat-dialog-container[1]/qmt-individual-cost-modal[1]/mat-dialog-content[1]/form[1]/div[2]/qmt-new-input[1]/div[1]/input[1]&#xd;
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[2]/div[2]/div[1]/mat-dialog-container[1]/qmt-individual-cost-modal[1]/mat-dialog-content[1]/form[1]/div[2]/qmt-new-input[1]/div[1]/input[1]&#xd;
</value>
      <webElementGuid>b8cc2607-3543-4e5c-aef2-302303aca63d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
