<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sequence</name>
   <tag></tag>
   <elementGuidId>522bc5b8-5060-4765-a375-bbd59f9af179</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@type='number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@type='number']</value>
      <webElementGuid>fb5bafc2-8e27-4887-833d-104bd584ee51</webElementGuid>
   </webElementProperties>
</WebElementEntity>
