<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Division</name>
   <tag></tag>
   <elementGuidId>34eb7fe0-b8a4-4a94-9b0d-e05bd3d21714</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.label.ng-tns-c125-33</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div/ng-list-item/div/div/ng-list-item/div/mat-list-item/span/a/div/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/super-admin/cost-center/individual/division/list</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4f5817cb-798a-4a12-9550-e621edbad0b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>label ng-tns-c125-33</value>
      <webElementGuid>52cf2228-55f1-4133-b37b-5b2083cfcb80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Division</value>
      <webElementGuid>f8754b43-69cb-41ae-b3ba-c85f24f51a11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/super-admin/cost-center/individual/division/list</value>
      <webElementGuid>ef54e73b-9480-4dfb-82e2-964d1ba16f07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ng-list-item/div/div/ng-list-item/div/mat-list-item/span/a/div/span</value>
      <webElementGuid>5c0e0128-6a50-4ad2-ad3f-522d5526ae07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Division' or . = 'Division')]</value>
      <webElementGuid>9111b936-0624-4b1c-9e29-62337560ee77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
