<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Department</name>
   <tag></tag>
   <elementGuidId>a13993b4-7fd3-4a13-b801-c20b7505a3a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.label.ng-tns-c125-36</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div/ng-list-item/div/div/ng-list-item[4]/div/mat-list-item/span/a/div/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/super-admin/cost-center/individual/department/list[count(. | //*[(text() = 'Department' or . = 'Department')]) = count(//*[(text() = 'Department' or . = 'Department')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3078c645-deff-4307-b420-c8e83a529cdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>label ng-tns-c125-36</value>
      <webElementGuid>14446f77-38a4-4cb8-8c1c-705e4c81cd89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Department</value>
      <webElementGuid>179c3c83-4139-4170-acb9-f9d67758bf2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/super-admin/cost-center/individual/department/list</value>
      <webElementGuid>d1ed1173-8136-4488-98da-d44607155685</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ng-list-item/div/div/ng-list-item[4]/div/mat-list-item/span/a/div/span</value>
      <webElementGuid>656d15ce-30b5-43fe-bb31-cc5bba7f8469</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Department' or . = 'Department')]</value>
      <webElementGuid>acc997f8-c668-4f50-9114-39a68be48eba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
