<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Region</name>
   <tag></tag>
   <elementGuidId>95bce7c2-4dcb-4c19-a652-4c0710e38d88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.label.ng-tns-c125-34</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div/ng-list-item/div/div/ng-list-item[2]/div/mat-list-item/span/a/div/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/super-admin/cost-center/individual/region/list</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>243fb8c3-82d2-4797-a5a4-f1966e86844b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>label ng-tns-c125-34</value>
      <webElementGuid>6104b821-c5df-4daa-b111-1ed3d6fd2c12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Region</value>
      <webElementGuid>a5c8b329-c78f-458b-a32a-d692019fed84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/super-admin/cost-center/individual/region/list</value>
      <webElementGuid>522c55b9-6134-496d-815e-3422d889cc3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ng-list-item/div/div/ng-list-item[2]/div/mat-list-item/span/a/div/span</value>
      <webElementGuid>a9c9118f-3853-474c-8a03-7225d99526ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Region' or . = 'Region')]</value>
      <webElementGuid>43577267-b55d-4d51-bdc8-d760a3d04d30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
