<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputpassword</name>
   <tag></tag>
   <elementGuidId>d80dbf4d-c112-40d0-b279-49f0a94956cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='password']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>365e5cbc-ba31-415a-817f-47dd75cd606b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>bfc8ba10-8d49-4e27-98ff-cfad7bec11fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your password</value>
      <webElementGuid>ed732c14-856a-4062-90ae-3430ae5b0097</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-4 py-[14px] border-solid border-[#5B5B5B] border rounded-lg w-full outline-primary-dark text-[#5B5B5B] text-sm ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>d7614b3f-b3d8-4151-8c6e-f7c8348ee2d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>b3b83326-d85f-4881-a81c-9151d24ca9a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography mat-app-background&quot;]/qm-root[1]/qmt-login[@class=&quot;ng-star-inserted&quot;]/form[@class=&quot;w-full ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;h-screen w-screen flex justify-start items-center&quot;]/div[@class=&quot;relative w-[35%] flex justify-center items-center bg-white h-full&quot;]/div[@class=&quot;w-[75%]&quot;]/div[@class=&quot;mt-5 mb-2&quot;]/div[@class=&quot;relative&quot;]/input[@class=&quot;px-4 py-[14px] border-solid border-[#5B5B5B] border rounded-lg w-full outline-primary-dark text-[#5B5B5B] text-sm ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>72b9f6c8-e19c-4703-816b-87207cff1cd1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='password']</value>
      <webElementGuid>94ccdb59-23cf-4ee9-8189-e67d642ffb97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>e975b69d-9535-437c-9246-35fad99836cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter your password' and @type = 'password']</value>
      <webElementGuid>7406b1da-1d94-4811-881c-4d2ef25022ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
