<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textareaNote 2</name>
   <tag></tag>
   <elementGuidId>408da62c-6973-485f-8e80-88f3856673dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='Note 2']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html[1]/body[1]/qm-root[1]/qmt-layout[1]/qmt-navigation[1]/mat-sidenav-container[1]/mat-sidenav-content[1]/div[1]/div[1]/qmt-union-code-form[1]/form[1]/div[1]/div[2]/div[8]/div[1]/div[1]/qmt-textarea-input[2]/div[1]/mat-form-field[1]/div[1]/div[1]/div[3]/textarea[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>eb0a55f1-3c1b-409a-a343-a5827fd6d98b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control text-sm text-[#91919180] font-medium ng-tns-c99-43 ng-untouched ng-valid cdk-text-field-autofill-monitored ng-dirty</value>
      <webElementGuid>59c10d12-55fd-499b-9fd4-f8e396ec2eb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-id</name>
      <type>Main</type>
      <value>Note 2</value>
      <webElementGuid>02b66e5c-8cf7-45b8-a8fc-9f8bce883390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-model</name>
      <type>Main</type>
      <value>N</value>
      <webElementGuid>0f230ac3-ad89-4f3b-8b9b-fad79c2ca28f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7f35d4a0-8d7e-4ec1-9992-496d3c1a16c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Note 2</value>
      <webElementGuid>3bbab800-4938-470a-b2a7-0e20279fa05f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>710613f8-6a38-4af7-a942-5e7e776cdacc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8cbcc762-7247-4673-a1de-a91c60274be1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/qm-root[1]/qmt-layout[1]/qmt-navigation[1]/mat-sidenav-container[1]/mat-sidenav-content[1]/div[1]/div[1]/qmt-union-code-form[1]/form[1]/div[1]/div[2]/div[8]/div[1]/div[1]/qmt-textarea-input[2]/div[1]/mat-form-field[1]/div[1]/div[1]/div[3]/textarea[1]</value>
      <webElementGuid>155bc152-58d2-4600-ba8f-705a1cc1ab53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='Note 2']</value>
      <webElementGuid>2e014dd4-eb6c-42ac-9e79-76ffcf403d36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//qmt-textarea-input[2]/div/mat-form-field/div/div/div[3]/textarea</value>
      <webElementGuid>4563f89f-f63d-47b7-989b-1c5065c91d74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'Note 2']</value>
      <webElementGuid>7f841189-8d63-4d05-b87b-17b194768d9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
