<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_I</name>
   <tag></tag>
   <elementGuidId>b35340ef-f18a-4c31-bf4f-7cedcc514fdc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-toolbar/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3c1fe182-5021-4026-a8ed-2dd9ebaffe25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e18c5b35-69ea-4c1e-904d-cc0be8ed3dbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-menu-trigger cursor-pointer ml-[10px] w-10 h-10 aspect-square bg-[#F1F1F9] flex justify-center items-center text-[#4A429E] text-5 font-semibold uppercase rounded-full</value>
      <webElementGuid>c4da4ae3-16d5-4b39-95be-7d90272fa1a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> I </value>
      <webElementGuid>b5c158bf-58ea-4967-a00a-3003ad7a2bef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography mat-app-background&quot;]/qm-root[1]/qmt-layout[@class=&quot;ng-star-inserted&quot;]/qmt-navigation[1]/mat-sidenav-container[@class=&quot;mat-drawer-container mat-sidenav-container sidenav-container&quot;]/mat-sidenav-content[@class=&quot;mat-drawer-content mat-sidenav-content&quot;]/mat-toolbar[@class=&quot;mat-toolbar sticky top-0 !py-4 !pl-8 !pr-6 border-b flex items-center justify-between z-[200] mat-primary mat-toolbar-single-row&quot;]/div[@class=&quot;flex items-center gap-5&quot;]/div[@class=&quot;mat-menu-trigger cursor-pointer ml-[10px] w-10 h-10 aspect-square bg-[#F1F1F9] flex justify-center items-center text-[#4A429E] text-5 font-semibold uppercase rounded-full&quot;]</value>
      <webElementGuid>c3b9d5b3-d07a-4fe9-98a3-562f047dcaa6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-toolbar/div[2]/div</value>
      <webElementGuid>bfe84968-ea96-4198-b261-b5869d69b3ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' I ' or . = ' I ')]</value>
      <webElementGuid>8815368b-e3ba-401b-9cc8-e48d7dc1c24c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
