<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_add Add Equipment Type</name>
   <tag></tag>
   <elementGuidId>dde6d203-e78d-4608-aafd-d084986fc83b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='add-new-button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#add-new-button</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'add-new-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a69ba865-d89a-42d6-8894-d5f88f14c9cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>2c647d80-a192-439d-8e59-57dd56111b73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>add-new-button</value>
      <webElementGuid>659cab9a-cc95-4400-8ca2-34060cbb76db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-focus-indicator !pl-2 mat-flat-button mat-button-base mat-primary cdk-focused cdk-mouse-focused</value>
      <webElementGuid>0c0b6a02-4bfe-4785-a559-6cca52ee5683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-color</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>4f9c79e7-c576-4bec-9155-671871d8c345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>add Add Equipment Type </value>
      <webElementGuid>422cfa13-5d46-4213-bbb9-ea19cd8e66c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-new-button&quot;)</value>
      <webElementGuid>a5289765-6d15-41f1-a20e-4d87fe87d756</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='add-new-button']</value>
      <webElementGuid>4dc456fb-58ec-4dc0-b01e-0fb644d6b2c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
      <webElementGuid>e8789f41-231a-4099-be48-289b9b45414c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'add-new-button' and (text() = 'add Add Equipment Type ' or . = 'add Add Equipment Type ')]</value>
      <webElementGuid>2eabf72a-1321-42af-bd20-348bca39ec25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
