<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ng-tns-c168-47 p-autocomplete-input p_053656</name>
   <tag></tag>
   <elementGuidId>df274de6-a387-4f42-b2f9-26b2da7d1cd5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.ng-tns-c168-47.p-autocomplete-input.p-inputtext.p-component.p-autocomplete-dd-input.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9f849a30-8ee8-4231-be49-7866948c1247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>a7cb3827-95a3-4f6c-b326-dbb218b03240</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>searchbox</value>
      <webElementGuid>da1c0fc2-4aac-40b6-99d5-401c50685fc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c168-47 p-autocomplete-input p-inputtext p-component p-autocomplete-dd-input ng-star-inserted</value>
      <webElementGuid>309d08a4-4939-473a-8545-3022e190fca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ff36c8dd-1a91-4944-abf5-a7232b734a3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>17af5be5-88ef-4671-abef-5df010a9e6fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Base UOM&quot;)/span[@class=&quot;ng-tns-c168-47 p-autocomplete p-component p-autocomplete-dd&quot;]/input[@class=&quot;ng-tns-c168-47 p-autocomplete-input p-inputtext p-component p-autocomplete-dd-input ng-star-inserted&quot;]</value>
      <webElementGuid>433315f6-435c-439b-b885-a09e30f3ff17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[3]</value>
      <webElementGuid>ed00d1cf-1ebf-41d9-8927-bf3d127cc1fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p-autocomplete[@id='Base UOM']/span/input</value>
      <webElementGuid>2ada77b3-ea5f-4100-bca1-61d7ca766109</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-autocomplete/span/input</value>
      <webElementGuid>64f70168-627c-4a6a-91c7-0cabe9ade8f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>5ce87ca9-8a97-4cef-ad60-a41ca909920d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
