<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-checkbox_</name>
   <tag></tag>
   <elementGuidId>8ea61ddf-8ffb-4e5d-8b65-53837ef9f3eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-checkbox-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-checkbox[@id='mat-checkbox-3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-checkbox</value>
      <webElementGuid>93c291c1-b292-4f6c-b62b-572efa5f2436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>ae897ea6-41ed-402e-a974-fe431b824271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-checkbox mt-2 mat-primary ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>8fcf1a54-b8ef-404d-a804-2286169dcc81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-color</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>1cdaf032-364e-42d5-a340-c41c323f8892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>is_enabled</value>
      <webElementGuid>60a66aca-b6ff-4a70-b4c1-665e38f68f44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-checkbox-3</value>
      <webElementGuid>daa0f9ff-9375-4e45-bbf4-b333ef825a9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> </value>
      <webElementGuid>cdf1f913-d596-43e4-a89e-dce09a7d91ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-checkbox-3&quot;)</value>
      <webElementGuid>e2fe52ef-157f-4f64-bf76-45ccb0cc89fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-checkbox[@id='mat-checkbox-3']</value>
      <webElementGuid>7ab53dae-7b59-4169-b30a-35a6ca08dd3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/mat-checkbox</value>
      <webElementGuid>d7856388-c86c-4898-8aa6-3fd431d1be9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-checkbox[@id = 'mat-checkbox-3' and (text() = ' ' or . = ' ')]</value>
      <webElementGuid>95a81bcc-b5e1-4752-82ee-c53be6751c34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
