<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_UOM</name>
   <tag></tag>
   <elementGuidId>ca921f88-f178-4dbf-9969-4dab2117f70b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.label.ng-tns-c125-32</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div/ng-list-item[5]/div/mat-list-item/span/a/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>121b0335-dfb8-4b1e-9c3d-a92aa780fe48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>label ng-tns-c125-32</value>
      <webElementGuid>0385597e-0258-4660-aa43-84e3a8de0322</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>UOM</value>
      <webElementGuid>3fe3c677-27f5-4d76-8f31-67cd8ab8d8fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography mat-app-background&quot;]/qm-root[1]/qmt-layout[@class=&quot;ng-star-inserted&quot;]/qmt-navigation[1]/mat-sidenav-container[@class=&quot;mat-drawer-container mat-sidenav-container sidenav-container&quot;]/mat-sidenav[@class=&quot;mat-drawer mat-sidenav sidenav relative ng-tns-c131-1 ng-trigger ng-trigger-transform mat-drawer-side mat-drawer-opened mat-sidenav-fixed ng-star-inserted&quot;]/div[@class=&quot;mat-drawer-inner-container ng-tns-c131-1&quot;]/ng-material-multilevel-menu[@class=&quot;ng-tns-c131-1&quot;]/div[@class=&quot;amml-container my-custom-class normal-case ng-star-inserted&quot;]/mat-list[@class=&quot;mat-list mat-list-base&quot;]/ng-list-item[@class=&quot;ng-tns-c125-22 ng-star-inserted&quot;]/div[@class=&quot;amml-menu-container ng-tns-c125-22&quot;]/div[@class=&quot;ng-tns-c125-22 ng-trigger ng-trigger-SlideInOut ng-star-inserted level-2 amml-submenu has-amml-submenu&quot;]/ng-list-item[@class=&quot;ng-tns-c125-32 ng-tns-c125-22 ng-star-inserted&quot;]/div[@class=&quot;amml-menu-container ng-tns-c125-32&quot;]/mat-list-item[@class=&quot;mat-list-item mat-focus-indicator mat-ripple ng-tns-c125-32 ng-star-inserted amml-item level-2-submenulevel-4&quot;]/span[@class=&quot;mat-list-item-content&quot;]/a[@class=&quot;anml-link ng-tns-c125-32 ng-star-inserted&quot;]/div[@class=&quot;anml-data ng-tns-c125-32 ng-star-inserted&quot;]/span[@class=&quot;label ng-tns-c125-32&quot;]</value>
      <webElementGuid>5211971d-0b4d-4817-b092-a0870f534f74</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ng-list-item[5]/div/mat-list-item/span/a/div/span</value>
      <webElementGuid>7ee48fa1-4c49-40b6-a4d0-0ec7352e2bcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'UOM' or . = 'UOM')]</value>
      <webElementGuid>d036b1ae-d4a2-4227-851f-8ebd2d2c1a2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
